/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq;


import com.example.backend.jooq.tables.Customer;
import com.example.backend.jooq.tables.Lot;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_CUSTOMER_CODE = Internal.createIndex(DSL.name("idx_customer_code"), Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.CUSTOMER_CODE }, false);
    public static final Index IDX_CUSTOMER_INN = Internal.createIndex(DSL.name("idx_customer_inn"), Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.CUSTOMER_INN }, false);
    public static final Index IDX_LOT_CUSTOMER_CODE = Internal.createIndex(DSL.name("idx_lot_customer_code"), Lot.LOT, new OrderField[] { Lot.LOT.CUSTOMER_CODE }, false);
}
