/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq;


import com.example.backend.jooq.tables.Customer;
import com.example.backend.jooq.tables.Databasechangeloglock;
import com.example.backend.jooq.tables.Lot;
import com.example.backend.jooq.tables.records.CustomerRecord;
import com.example.backend.jooq.tables.records.DatabasechangeloglockRecord;
import com.example.backend.jooq.tables.records.LotRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerRecord> CUSTOMER_CUSTOMER_CODE_KEY = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("customer_customer_code_key"), new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE }, true);
    public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("customer_pkey"), new TableField[] { Customer.CUSTOMER.ID }, true);
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<LotRecord> LOT_PKEY = Internal.createUniqueKey(Lot.LOT, DSL.name("lot_pkey"), new TableField[] { Lot.LOT.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CustomerRecord, CustomerRecord> CUSTOMER__FK_CUSTOMER_PARENT = Internal.createForeignKey(Customer.CUSTOMER, DSL.name("fk_customer_parent"), new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE_MAIN }, Keys.CUSTOMER_CUSTOMER_CODE_KEY, new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE }, true);
    public static final ForeignKey<LotRecord, CustomerRecord> LOT__FK_LOT_CUSTOMER = Internal.createForeignKey(Lot.LOT, DSL.name("fk_lot_customer"), new TableField[] { Lot.LOT.CUSTOMER_CODE }, Keys.CUSTOMER_CUSTOMER_CODE_KEY, new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE }, true);
}
