/*
 * This file is generated by jOOQ.
 */
package com.example.backend.jooq.tables.records;


import com.example.backend.jooq.tables.Lot;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LotRecord extends UpdatableRecordImpl<LotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lot.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lot.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.lot.lot_name</code>.
     */
    public void setLotName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lot.lot_name</code>.
     */
    public String getLotName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lot.customer_code</code>.
     */
    public void setCustomerCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lot.customer_code</code>.
     */
    public String getCustomerCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lot.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lot.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.lot.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lot.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.lot.nds_rate</code>.
     */
    public void setNdsRate(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lot.nds_rate</code>.
     */
    public String getNdsRate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.lot.place_delivery</code>.
     */
    public void setPlaceDelivery(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lot.place_delivery</code>.
     */
    public String getPlaceDelivery() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.lot.date_delivery</code>.
     */
    public void setDateDelivery(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.lot.date_delivery</code>.
     */
    public LocalDateTime getDateDelivery() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.lot.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.lot.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.lot.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.lot.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LotRecord
     */
    public LotRecord() {
        super(Lot.LOT);
    }

    /**
     * Create a detached, initialised LotRecord
     */
    public LotRecord(Long id, String lotName, String customerCode, BigDecimal price, String currencyCode, String ndsRate, String placeDelivery, LocalDateTime dateDelivery, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Lot.LOT);

        setId(id);
        setLotName(lotName);
        setCustomerCode(customerCode);
        setPrice(price);
        setCurrencyCode(currencyCode);
        setNdsRate(ndsRate);
        setPlaceDelivery(placeDelivery);
        setDateDelivery(dateDelivery);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
