spring.application.name=backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/analyze_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JOOQ Configuration
spring.jooq.sql-dialect=postgres

# Server
server.port=8080

# Logging
logging.level.com.example.backend=DEBUG
logging.level.org.jooq=DEBUG
logging.level.org.springframework=INFO