# PostgreSQL connection
url=jdbc:postgresql://localhost:5432/analyze_db
username=postgres
password=root
driver=org.postgresql.Driver

# Liquibase settings
changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
logLevel=info
